---
driver:
  name: docker
  hostname: openssh.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: openssh
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - openssh
  pillars:
    top.sls:
      base:
        "*":
          - openssh
  dependencies:
    - name: linux
      repo: git
      source: "https://github.com/salt-formulas/salt-formula-linux"

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:

  - name: openssh_client
    provisioner:
      pillars-from-files:
        openssh.sls: tests/pillar/openssh_client.sls

  - name: openssh_server
    provisioner:
      pillars-from-files:
        openssh.sls: tests/pillar/openssh_server.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
